version: "3"
services:
    wso2-api-manager:
        image: "wso2/wso2am:4.1.0"
        hostname: "wso2-api-manager"
        ports:
            - "9443:9443"
            - "8243:8243"
            - "8280:8280"
        volumes :
            - "./wso2am-4.1.0/repository/conf/deployment.toml:/home/wso2carbon/wso2am-4.1.0/repository/conf/deployment.toml"
            - "./wso2am-4.1.0/repository/database:/home/wso2carbon/wso2am-4.1.0/repository/database"
        restart: "always"
